export const LandingPageLanguage = {
  en: {
    welcomeText: "Unlimited movies, TV shows and more",
    watchText: "Ready To Watch?",
    getStarted: "GET STARTED",
    signInBtn: "Sign in",
  },
  hindi: {
    welcomeText: "असीमित फिल्में, टीवी शो और बहुत कुछ",
    watchText: "देखने के लिए तैयार हैं?",
    getStarted: "आरंभ करें",
    signInBtn: "दाखिल करना",
  },
  spanish: {
    welcomeText: "Películas, programas de TV y más ilimitados",
    watchText: "¿Listo para ver?",
    getStarted: "COMENZAR",
    signInBtn: "Acceder",
  },
  french: {
    welcomeText: "Films, séries et plus sans limites",
    watchText: "Prêt à regarder ?",
    getStarted: "COMMENCER",
    signInBtn: "Se connecter",
  },
  german: {
    welcomeText: "Unbegrenzte Filme, Serien und mehr",
    watchText: "Bereit zum Anschauen?",
    getStarted: "LOS GEHT'S",
    signInBtn: "Anmelden",
  },
  japanese: {
    welcomeText: "無制限の映画、TV番組など",
    watchText: "視聴する準備はできましたか？",
    getStarted: "はじめる",
    signInBtn: "サインイン",
  },
  arabic: {
    welcomeText: "أفلام وبرامج تلفزيونية غير محدودة والمزيد",
    watchText: "هل أنت مستعد للمشاهدة؟",
    getStarted: "ابدأ الآن",
    signInBtn: "تسجيل الدخول",
  },
  portuguese: {
    welcomeText: "Filmes, séries e mais sem limites",
    watchText: "Pronto para assistir?",
    getStarted: "COMEÇAR",
    signInBtn: "Entrar",
  },
  russian: {
    welcomeText: "Безграничные фильмы, сериалы и больше",
    watchText: "Готовы смотреть?",
    getStarted: "НАЧАТЬ",
    signInBtn: "Войти",
  },
  chinese: {
    welcomeText: "无限的电影、电视节目和更多",
    watchText: "准备观看了吗？",
    getStarted: "开始使用",
    signInBtn: "登录",
  },
  italian: {
    welcomeText: "Film, serie TV e tanto altro senza limiti",
    watchText: "Pronto a guardare?",
    getStarted: "INIZIA",
    signInBtn: "Accedi",
  },
  korean: {
    welcomeText: "무제한 영화, TV 프로그램 등",
    watchText: "시청할 준비가 되셨나요?",
    getStarted: "시작하기",
    signInBtn: "로그인",
  },
  bengali: {
    welcomeText: "অসীম চলচ্চিত্র, টিভি শো এবং আরও অনেক কিছু",
    watchText: "দেখতে প্রস্তুত?",
    getStarted: "শুরু করুন",
    signInBtn: "সাইন ইন",
  },
};

export const loginLanguage = {
  en: {
    signIn: "Sign In",
    signUp: "Sign Up",
    userPlaceholder: "Username",
    emailPlaceholder: "Email",
    newUser: "New to Netflix?",
    existUser: "Already have an account!",
    nowSignUp: "Sign up now",
    nowSignIn: "Sign in now",
    password: "Password",
  },
  hindi: {
    signIn: "दाखिल करना",
    signUp: "साइन अप करें",
    userPlaceholder: "उपयोगकर्ता नाम",
    emailPlaceholder: "ईमेल",
    newUser: "नेटफ्लिक्स पर नये हैं?",
    existUser: "पहले से खाता है क्या!",
    nowSignUp: " अभी रजिस्टर करें",
    nowSignIn: "अभी लॉग इन करें",
    password: "पासवर्ड",
  },
  spanish: {
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    userPlaceholder: "Nombre de usuario",
    emailPlaceholder: "Correo electrónico",
    newUser: "¿Nuevo en Netflix?",
    existUser: "¡Ya tienes una cuenta!",
    nowSignUp: "Regístrate ahora",
    nowSignIn: "Iniciar sesión ahora",
    password: "contraseña",
  },
  french: {
    signIn: "Se connecter",
    signUp: "S'inscrire",
    userPlaceholder: "Nom d'utilisateur",
    emailPlaceholder: "E-mail",
    newUser: "Nouveau sur Netflix ?",
    existUser: "Vous avez déjà un compte !",
    nowSignUp: "Inscrivez-vous maintenant",
    nowSignIn: "Connectez-vous maintenant",
    password: "Mot de passe",
  },
  german: {
    signIn: "Anmelden",
    signUp: "Registrieren",
    userPlaceholder: "Benutzername",
    emailPlaceholder: "E-Mail",
    newUser: "Neu bei Netflix?",
    existUser: "Sie haben bereits ein Konto!",
    nowSignUp: "Jetzt registrieren",
    nowSignIn: "Jetzt anmelden",
    password: "Passwort",
  },
  japanese: {
    signIn: "サインイン",
    signUp: "サインアップ",
    userPlaceholder: "ユーザー名",
    emailPlaceholder: "メールアドレス",
    newUser: "Netflixは初めてですか？",
    existUser: "すでにアカウントをお持ちですか？",
    nowSignUp: "今すぐ登録",
    nowSignIn: "今すぐサインイン",
    password: "パスワード",
  },
  arabic: {
    signIn: "تسجيل الدخول",
    signUp: "اشتراك",
    userPlaceholder: "اسم المستخدم",
    emailPlaceholder: "البريد الإلكتروني",
    newUser: "جديد على Netflix؟",
    existUser: "هل لديك حساب بالفعل؟",
    nowSignUp: "اشترك الآن",
    nowSignIn: "سجل الدخول الآن",
    password: "كلمة المرور",
  },
  portuguese: {
    signIn: "Entrar",
    signUp: "Inscrever-se",
    userPlaceholder: "Nome de usuário",
    emailPlaceholder: "E-mail",
    newUser: "Novo no Netflix?",
    existUser: "Já tem uma conta?",
    nowSignUp: "Inscreva-se agora",
    nowSignIn: "Entre agora",
    password: "Senha",
  },
  russian: {
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    userPlaceholder: "Имя пользователя",
    emailPlaceholder: "Эл. почта",
    newUser: "Впервые в Netflix?",
    existUser: "Уже есть аккаунт?",
    nowSignUp: "Зарегистрироваться сейчас",
    nowSignIn: "Войти сейчас",
    password: "Пароль",
  },
  chinese: {
    signIn: "登录",
    signUp: "注册",
    userPlaceholder: "用户名",
    emailPlaceholder: "电子邮件",
    newUser: "新用户？",
    existUser: "已有账号？",
    nowSignUp: "立即注册",
    nowSignIn: "立即登录",
    password: "密码",
  },
  italian: {
    signIn: "Accedi",
    signUp: "Iscriviti",
    userPlaceholder: "Nome utente",
    emailPlaceholder: "E-mail",
    newUser: "Sei nuovo su Netflix?",
    existUser: "Hai già un account?",
    nowSignUp: "Iscriviti ora",
    nowSignIn: "Accedi ora",
    password: "Password",
  },
  korean: {
    signIn: "로그인",
    signUp: "가입하기",
    userPlaceholder: "사용자 이름",
    emailPlaceholder: "이메일",
    newUser: "Netflix 회원이 아니신가요?",
    existUser: "이미 계정이 있으신가요?",
    nowSignUp: "지금 가입하기",
    nowSignIn: "지금 로그인하세요",
    password: "비밀번호",
  },
  bengali: {
    signIn: "সাইন ইন",
    signUp: "সাইন আপ",
    userPlaceholder: "ব্যবহারকারীর নাম",
    emailPlaceholder: "ইমেইল",
    newUser: "Netflix-এ নতুন?",
    existUser: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
    nowSignUp: "এখনই সাইন আপ করুন",
    nowSignIn: "এখনই সাইন ইন করুন",
    password: "পাসওয়ার্ড",
  },
};
